spring:
  datasource:
    url: jdbc:mysql://database-1.c964qom4sij2.ap-southeast-1.rds.amazonaws.com:3306/shop_schema?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: wjy1155199702
    password: 56231489y
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
#  config-location: classpath:mybatis/mybatis-config.xml   #全局配置
#  mapper-locations: classpath:mybatis/mapper/*.xml    #sql映射文件配置
  type-aliases-package: com.example.backend.entity #实体位置
